---
title: "MATH630-HW1"
author: "Joshua Burkhart"
date: "October 13, 2015"
output: pdf_document
---
HLO Gapminder

    Is it a data.frame, a matrix, a vector, a list?
    What is the unit of analysis in the dataset?
    How many variables/columns?
    How many rows/observations?
    Which variables are continuous?
    Which variables are discrete?
    Which variables are categorical?
    How many levels do they have?
    What about missing data for any variables?

Numerical and counting detective work

    Pick one quantitative variable to explore using descriptive statistics as discussed in class.
        Characterize the range of possible values, max vs. min, etc.- does it make sense?
        What's the center? What's the spread? What's the shape?
        Feel free to use summary statistics or tables. You don't need to re-summarise summarised data for us. It is one thing to be able to get R to give you what you ask for. It is another to interpret what R gives you. We are more interested in the latter here, but also that you can do the former without errors.
        Comment on representativeness of measures of central tendency, given the spread and shape.
    Pick one categorical variable and generate the n's (in whatever the appropriate "unit of analysis" is) and proportions of the sample that contribute to each level of that variable.
        Which level contains the smallest number of observations? The largest?
    Generate your descriptive statistics again, now stratified by the different levels of your categorical variable.
        How did any of your initial observations of the quantitative variable change?
        Foreshadowing: look for differences in both center and spread across categories. Think about what this means in terms of possible comparisons between means across different levels of that factor.

Graphical detective work


    Graphically explore your one quantitative variable using histograms and boxplots. See the exploratory data analysis link for example R code.
        What are you looking for in each plot?
        Do you notice anything interesting/puzzling/surprising?
        Look back at your descriptive statistics for your variable. Comment on the descriptive value of the numbers in light of your visualizations. Do a quick sanity check- does everything look consistent across numerical and graphical depictions of your data?
    Add your one categorical variable to the mix and graphically explore your quantitative variable using any of the combination plots discussed in class. Your new plot must account for the categorical variable, either by facetting by levels of that variable, setting an aesthetic (color, shape, etc.) to differ across levels, or stratifying the x-axis by the different levels of your categorical variable. See the exploratory data analysis link for ideas. We want to see you exploring multiple types of plots, and each plot should include at least 2 "layers" of information. Sampling 100 random rows from the dataset is a valid strategy here (reference last slide from Class 2 EDA class) if you want to compare big n/small n types of plots.

In-depth detective work

Manipulate and further explore the gapminder dataset with the dplyr package, complemented by visualizations made with ggplot2. Pick at least two of the tasks below from the task menu and approach each with a table and figure.

    dplyr should be your main data manipulation tool
    ggplot2 should be your main visualization tool

Make observations about what your tables/figures show and about the process. If you want to do something comparable but different, i.e. swap one quantitative variable for another- go for it!

You do not have to use tidyr or otherwise worry about reshaping your tables. Many of your tables may not be formatted perfectly in the report. Simply printing dplyr tabular output is fine. For all things, graphical and tabular, if you're dissatisfied with a result, discuss the problem, what you tried to do to fix it, and move on.

Task menu



    Get the maximum and minimum of GDP per capita for all continents.

    Look at the spread of GDP per capita across countries within the continents.

    How does life expectancy vary across different continents?

    Report the absolute and/or relative abundance of countries with low life expectancy over time by continent: Compute some measure of worldwide life expectancy - you decide - a mean or median or some other quantile or perhaps your current age. Then determine how many countries on each continent have a life expectancy less than this benchmark, for each year.

    Make up your own! Look back at our Class 2 slides for dplyr example ideas with the diamonds dataset, and the package vignettes for other ideas.

Companion graphs

For each table, make sure to include a relevant figure. One tip for starting is to draw out on paper what you want your x- and y-axis to be first and what your geom is; that is, start by drawing the plot you want ggplot to give you. Your figure does not have to depict every single number present in the table. Use your judgement. It just needs to complement the table, add context, and allow for some sanity checking.

Notice which figures are easy/hard to make, and whether the visualization adds clarity, detracts from, or is completely redundant (and therefore probably unnecessary) with respect to the tabular display.

Report your process

You're encouraged to reflect on what was hard/easy, problems you solved, helpful tutorials you read, etc.
